# Generated by Django 6.0.4 on 2026-04-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('CHECKED', 'Checked'), ('RESOLVED', 'Resolved')], default='REPORTED', max_length=20),
        ),
    ]
