# Generated by Django 6.0.4 on 2026-05-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ticket_checked_at_ticket_reported_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Higher', 'Higher'), ('Medium', 'Medium'), ('Normal', 'Normal')], default='Normal', max_length=50),
        ),
    ]
